### ISSUE TITLE
In the description of the adapter included a closing bracket in the link. 

### ISSUE THREAD

**Issue by badenbaden** [nisiode/ioBroker.iogo#17]
In the description of the adapter included a closing bracket in the link. When switching to play.market shows that there is no page
`<a target="_blank" href="https://play.google.com/store/apps/details?id=de.nisnagel.iogo)">https://play.google.com/store/apps/details?id=de.nisnagel.iogo)</a>`

**Comment by nisiode** [comment]
fixed in version 0.4.5
