### ISSUE TITLE
Passwörter werden als Klartext angezeigt

### ISSUE THREAD

**Issue by santa81** [nisiode/ioBroker.iogo#18]
Unter Objekt bearbeiten system.adapter.iogo.0 RAW wird das Passwort als Klartext angezeigt, in anderen Adaptern wird dies nur verschlüsselt angezeigt

**Comment by nisiode** [comment]
hast du mal bitte ein Beispiel wo es verschlüsselt angezeigt wird

**Comment by santa81** [comment]
mqtt, sonoff, shelly, aber dabei fällt mir auf, es gibt auch andere die das nicht verschlüsseln
