### ISSUE TITLE
Feature Request: Push Nachrichten von DP aus

### ISSUE THREAD

**Issue by santa81** [nisiode/ioBroker.iogo#19]
Um einfacher Push Nachrichten von iobroker zu bekommen, wäre es genial wenn man über den Schraubenschlüssel eines Objekts/Datenpunkts in einem Reiter iogo bestimmte Kriterien auswählen könnte, also zum Beispiel:
1. Wenn DP true, dann Push Nachricht an iogo client x mit, title y und Nachricht z
2. Wenn DP größer, dann Push Wert an iogo 
usw.
Sicherlich ginge das auch über die App oder js, aber das ist nicht smart genug.

**Comment by nisiode** [comment]
wird demnächst umgesetzt analog dem telegram Adapter

**Comment by nisiode** [comment]
ist in der neuen Version 0.4.13 verfügbar

**Comment by santa81** [comment]
Bei DP mit simple true/false funktioniert es super.
Beim DP tr64, callmonitor, inbound, caller passiert nichts, keine Reaktion, auch im log ist nichts zu sehen.
DP wird auch bestätigt, also ack true ist vorhanden

**Comment by nisiode** [comment]
bitte mal das RAW des Objekts posten und wie genau der Wert geändert wird

**Comment by santa81** [comment]
`{
  "type": "state",
  "common": {
    "name": "caller",
    "type": "string",
    "role": "state",
    "custom": {
      "iogo.0": {
        "enabled": true,
        "alias": "",
        "offStatus": "",
        "onStatus": ""
      }
    }
  },
  "native": {},
  "_id": "tr-064-community.0.callmonitor.inbound.caller",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1570190596881
}`
der Wert selber ist dann einfach eine Telefonnummer

**Comment by nisiode** [comment]
Der Adapter "tr-064-community" ist nirgends offiziell gelistet. Hast du noch einen anderen Adapter bei dem etwas nicht geht?

**Comment by nisiode** [comment]
Sollte in Version 0.4.14 behoben sein

**Comment by santa81** [comment]
jupp, passt
