### ISSUE TITLE
Update stable version in repo to 0.5.4

### ISSUE THREAD

**Issue by GermanBluefox** [nisiode/ioBroker.iogo#27]
# Think about update stable version to 0.5.4
**Version**: stable=**0.4.17** (130 days old) => latest=**0.5.4** (24 days old)
**Installs**: stable=**330** (56.51%), latest=**114** (19.52%), total=**584**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L530)

**Comment by nisiode** [comment]
see https://github.com/nisiode/ioBroker.iogo/issues/26
