### ISSUE TITLE
Adapter verbindet sich nicht

### ISSUE THREAD

**Issue by E-Stegemann** [nisiode/ioBroker.iogo#34]
Hallo,
Ich habe den iogo Adapter installiert, mir einen Account erstellt und eine Jahreslizenz gekauft. Nun ist es so, dass der Adapter bei Eingabe meiner Account credentials sich nicht mit dem iogo Server verbindet. Die Statusleuchte steht auf Gelb. 
Irgendeiner eine Idee wieso? Würde die App gerne nutzen wollen.

Gruß und Danke,
Eric

**Comment by nisiode** [comment]
Bitte schicke mir eine Mail mit dem Log des Adapters was beim Start der Instanz geschrieben wird.

**Comment by E-Stegemann** [comment]
Mach ich heute Abend gleich. Vielen Dank schon mal im voraus.

**Comment by E-Stegemann** [comment]
Mail mit dem Log ist raus.

Gruß Eric

**Comment by nisiode** [comment]
Passwort reset hat geholfen
