### ISSUE TITLE
Add possibility to push images

### ISSUE THREAD

**Issue by braindead1** [nisiode/ioBroker.iogo#5]
With Telegram Messenger it's possible to send images e.g. from ip-cams. To be a full replacement for Telegram Messenger pushing images is needed.

Maybe this feature can be used to motivate users to pay for the ioGo App.

**Comment by nisiode** [comment]
Nice idea, have to check the traffic as traffic is not unlimited for free

**Comment by nisiode** [comment]
But the image will not be part of the notification.
The notification is only the alert, saying "hey a new image is availabe".
Then a small "show image" button is part of that notification.
When you click on that button, the app starts and shows the image.

Is that what you mean, more or less?

**Comment by braindead1** [comment]
Maybe it's possible to add an additional tab besides Home, Funktionen and Rooms called Notifications. Then all notifications can be accessed in this tab. Here also the images should be shown.

At best the image would also be shown in the notification bar, but your solution would be good, too.

**Comment by nisiode** [comment]
Added in v0.2.0 in combination with AppVersion v1.2.2 as paid feature

**Comment by braindead1** [comment]
I'm curious about the new feature, but although I'm beta tester of the app, I'm still with version 1.02.04. How is it possible to update to 1.2.2?

**Comment by nisiode** [comment]
1.02.04 is higher then 1.2.2(1.02.02)

**Comment by nisiode** [comment]
So sollte es aussehen wenn es klappt:
![screenshot_1543002874](https://user-images.githubusercontent.com/17888589/48958857-16041580-ef62-11e8-973b-46f0e1f08480.png)
![screenshot_1543002845](https://user-images.githubusercontent.com/17888589/48958856-16041580-ef62-11e8-967f-2e32927adf87.png)

**Comment by nisiode** [comment]
Muss mal nachsehen was da nicht geklappt hat

**Comment by nisiode** [comment]
Es gab noch einen Bug.

Bitte die App Version 1.2.6 (1.02.06) installieren und dann das Abo erneut abschliessen(vorher abo kündigen).

Version 1.2.6 müsste in den nächsten Minuten/Stunden als Beta online sichtbar sein

**Comment by braindead1** [comment]
Ich habe gerade die App und den Adapter aktualisiert und jetzt kommen auch die Bilder an. Es gibt allerdings ein Cache Problem: Wenn es bei mir an der Tür klingelt, dann schickt mir die Kamera 3 Bilder im Abstand von 10 Sekunden. In ioGo wird dann dreimal das erste Bild angezeigt. Mit Telegram gibt es hier kein Problem.

**Comment by nisiode** [comment]
Haben die drei Bilder unterschiedliche Dateinamen oder alle den gleichen?

**Comment by nisiode** [comment]
Probier mal bitte die neue Version 0.2.4 aus, ich habe nun den Pfad zum Bild eindeutig gemacht auch wenn der Dateiname immer der gleiche ist

**Comment by braindead1** [comment]
Ich habe den Adapter auf 0.2.4 aktualisiert. Das Problem besteht noch immer. Mir ist gerade zusätzlich aufgefallen, dass in der App auch bei den alten Nachrichten von gestern immer das aktuellste Bild angezeigt wird. Da die Bilder meiner Kamera einen Timestamp enthalten, kann ich das sehr gut verifizieren.

**Comment by nisiode** [comment]
bin dran...

**Comment by nisiode** [comment]
ich habe noch eine neue version 0.2.5 erstellt.
hoffentlich habe ich nun alles gefunden.

vielen dank für die Geduld, das Testen und das Feedback

**Comment by nisiode** [comment]
hast du wirklich Version 0.2.5 laufen?
poste mal bitte den Log vom Starten des Adapters.

probier ansonsten mal bitte ob ein upload und restart hilft:
`iobroker upload iogo`
`iobroker restart iogo`

**Comment by braindead1** [comment]
Laut ioBroker ist 0.2.5 installiert. Trotzdem habe ich gerade ein upload und restart gemacht. Jetzt ist zumindest das Problem behoben, dass immer das selbe Bild angezeigt wird. Dafür gibt es jetzt das Problem, dass die Bilder in der App manchmal nicht angezeigt werden. Leider kann ich das nicht reproduzieren.


Hier noch mein Log:

iogo.0 | 2018-11-27 22:01:16.666 | info | database initialized with 4 objects
iogo.0 | 2018-11-27 22:01:16.590 | info | database initialized with 4 states
iogo.0 | 2018-11-27 22:01:16.589 | info | database initialized with 27 enums
iogo.0 | 2018-11-27 22:01:16.143 | info | removed enums from remote database
iogo.0 | 2018-11-27 22:01:16.143 | info | removed objects from remote database
iogo.0 | 2018-11-27 22:01:16.142 | info | removed states from remote database
iogo.0 | 2018-11-27 22:01:16.139 | info | PRO features enabled
iogo.0 | 2018-11-27 22:01:16.138 | info | logged in as: DAS HABE ICH GELÖSCHT
iogo.0 | 2018-11-27 22:01:15.553 | info | device Braindead captured
iogo.0 | 2018-11-27 22:01:15.509 | info | initialize app devices
iogo.0 | 2018-11-27 22:01:15.487 | info | starting. Version 0.2.5 in /opt/iobroker/node_modules/iobroker.iogo, node: v6.14.4
iogo.0 | 2018-11-27 22:01:15.474 | info | States connected to redis: 127.0.0.1:6379

**Comment by nisiode** [comment]
ich hab noch ein Feinheiten angepasst.
wenn es nun keine Fehler mehr gibt, dann geb ich die Version frei für alle.

**Comment by nisiode** [comment]
Hab mich nochmal belesen.
Tatsächlich werden die Notification unterschiedlich behandelt wenn die App im Vordergrund oder im Hintergrund laufen.

Mit der ganz neuen Version (1.2.9) sollte nun auch im Bilder angezeigt werden, wenn die App im Hintergrund läuft.

**Comment by braindead1** [comment]
Top! Ich habe jetzt alle Konstellationen ausprobiert, die mir einfallen und jedesmal kommen die richtigen Bilder an und werden auch immer (spätestens nach Aktualisierung des Messages Tabs) angezeigt.

Folgende (kosmetische) Punkte sind mir noch aufgefallen:
- Wird nur das Bild geschickt, dann ist in der App unter dem Bild ein grauer Balken sichtbar. Den solltest Du ausblenden.
- Vor den drei Bildern lasse ich mir den Text "Es wurde geklingelt" schicken. Manchmal ist dann über dem Text in der App eine graue Fläche, die so aussieht, als würde da ein Bild fehlen.
- Anstatt bei den Nachrichten "Vor 1 Stunde" unter dem Titel zu zeigen, fände ich es besser die konkrete Zeit zu zeigen. Vielleicht könnte man das einstellbar machen.
- Von anderen Apps ist man es gewohnt eine Aktualisierung auszulösen, wenn man mit dem Finger nach unten wischt. In der App muss man bisher auf den Messages Tab drücken. Mich hat das am Anfang ziemlich verwirrt.
- Werden die Nachrichten irgendwann automatisch gelöscht? Falls nicht, wäre es gut, wenn man das einstellen könnte. Alternativ wäre ein Knopf gut, mit dem ältere bzw. alle Nachrichten gelöscht werden können.

Das sind alle meine Punkte zu den Nachrichten. Nochmals Danke für Deine Geduld!

**Comment by nisiode** [comment]
- Message ohne Text geht nicht, sollte auch im Log stehen
- Graue Fläche wird verkleinert
- Format "vor 1 Stunde" finde ich gut und lasse es vorerst so
- Aktualisierung geht automatisch, wir nochmal verbessert in 1.2.10
- Löschen geht bei jeder einzelnen Message über das "X" oben rechts, automatisch wird nix gelöscht

Ich schließe den Issue hier nun, wenn noch mehr Ideen kommen bitte einen neuen Issue aufmachen.
Oder gerne auch direkt hier, wenn es eher das Layout der App betrifft und nicht den ioBroker-Adapter:https://github.com/nisiode/ioGo/issues
