### ISSUE TITLE
Error 0.2

### ISSUE THREAD

**Issue by vr6syncro** [nisiode/ioBroker.iogo#9]
Gerade geupdatet und bekomme einen Fehler
`

ost.ioBroker | 2018-11-20 16:50:54.095 | error | instance system.adapter.iogo.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-11-20 16:50:54.095 | error | by controller[0]: at Function.Module._load (module.js:445:3) code: 'MODULE_NOT_FOUND' }
Caught | 2018-11-20 16:50:54.095 | error | by controller[0]: at tryModuleLoad (module.js:453:12)
Caught | 2018-11-20 16:50:54.095 | error | by controller[0]: at Module.load (module.js:494:32)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Object.Module._extensions..js (module.js:586:10)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Module._compile (module.js:577:32)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.iogo/main.js:34:25)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at require (internal/module.js:20:19)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Module.require (module.js:504:17)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Function.Module._load (module.js:424:25)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: at Function.Module._resolveFilename (module.js:476:15)
Caught | 2018-11-20 16:50:54.094 | error | by controller[0]: { Error: Cannot find module 'xhr2'
iogo.0 | 2018-11-20 16:50:54.077 | info | terminating
iogo.0 | 2018-11-20 16:50:53.642 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.iogo, node: v6.14.4

`

**Comment by nisiode** [comment]
Bitte mal v0.2.1 probieren

**Comment by ldittmar81** [comment]
Mit v0.2.1 läuft es bei mir wieder

**Comment by vr6syncro** [comment]
Ja bestätigt, läuft wieder
